[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build --workspace=apps/api"
]

[start]
cmd = "cd apps/api && npx prisma migrate deploy && npx prisma generate && node dist/server.js"

